### ISSUE TITLE
Inno Setup 5 dependency

### ISSUE THREAD

**Issue by Solidogen** [Stinger21/imageDeCap#78]
Tried bulding version 1.24, I was unable to do it, because of PostBuildEvent needs to run C:\Program Files (x86)\Inno Setup 5\Compil32.exe.

https://www.nuget.org/packages/Tools.InnoSetup/

This could be a good alternative to keep developing portable, what do you think?

**Comment by Stinger21** [comment]
Ooh that's really cool. Had no idea it existed as a nuget thing. Definitely
switching to that.

**Comment by Stinger21** [comment]
that inno nuget package made the resource includer (Costura.Fody) implode, so I just copy/pasted the binaries out of it to use directly instead. So that should work even though it's probably bad practice.
